### ISSUE TITLE
オプションの有無に関わらずscriptsがアルファベット順にソートされる

### ISSUE THREAD

**Issue by SnO2WMaN** [uetchy/prettier-plugin-fixpack#1]
これがfixpack側の仕様なのかどうかを正確に把握していないのですが，`.fixpackrc`で`sortedSubItems`から`scripts`を除外しても`package.json`で`scripts`がアルファベット順にソートされてしまうようです

**Comment by uetchy** [comment]
`fixpack`パッケージは内部ロジックをexportしておらず、それらの関数にアクセスできないため、代わりにfixpackの挙動を再実装しています（なので実は`fixpack`に依存していません）
そのような背景から今のところ`sortToTop`以外のプロパティに対応していませんが、他のプロパティもパースできるようになれば便利だと思います。
良ければPRを送っていただけませんか？

**Comment by SnO2WMaN** [comment]
おそらくfixpack自体scriptsの並び替えが正常に働いていないようで(機能の停止などもどうも出来ないらしい?),コード自体も古かったので自分で`package.json`の並び替えライブラリを自作することにしました.したがってこのIssueごと閉じることにします.回答ありがとうございます.
